version: "3"

services:

  nginx:
    container_name: nginx
    image: nginx:sguilher
    build:
      context: ./requirements/nginx
    ports:
      - 443:443
    restart: unless-stopped
    networks:
      - inception-network
    init: true
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
      # wordpress:
      #   condition: service_started
    # environment:
      # - VAR=value
    #   - COMPOSE_PROJECT_NAME
    # command: echo "I'm running ${COMPOSE_PROJECT_NAME}"

  wordpress:
    container_name: wordpress
    image: wordpress:sguilher
    build:
      context: ./requirements/wordpress
    volumes:
      - wordpress:/var/www/wordpress
    env_file: .env
    restart: unless-stopped
    depends_on:
      - mariadb
      # mariadb:
      #   condition: service_started
    networks:
      - inception-network
    init: true

  mariadb:
    container_name: mariadb
    image: mariadb:sguilher
    build:
      context: ./requirements/mariadb
      args:
        - DB_NAME
        - DB_ROOT
        - DB_ROOT_PASSWORD
        - DB_USER
        - DB_USER_PASSWORD
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    networks:
      - inception-network
    init: true

networks:
  inception-network:
    driver: bridge # default
    name: inception-network

# create the volumes to be used
volumes:
  mariadb:
    # the volume will be created in the local file system - default, not necessary
    driver: local
    driver_opts:
      type: none # it is not associated with any specific driver type
      # 'o' and 'device' are used together
      o: bind # specifieds that the volume should be bound to a directory in host machine
      device: /home/sguilher/data/mariadb # the directory to bind the volume
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/sguilher/data/wordpress