version: "1"

services:

  nginx:
    container_name: nginx
    image: nginx:sguilher
    build:
      context: ./requirements/nginx
    ports:
      - 443:443
    restart: unless-stopped
    networks:
      - inception-network
    init: true
    depends_on:
      - wordepress

  wordepress:
    container_name: wordpress
    image: wordpress:sguilher
    build:
      context: ./requirements/wordpress
    # volumes:
    #   - home/sguilher/data:./requirements/wordpress/app  # ?
    restart: unless-stopped
    depends_on:
      - mariadb
    networks:
      - inception-network
    init: true

  mariadb:
    container_name: mariadb
    image: mariadb:sguilher
    build:
      context: ./requirements/mariadb
    # volumes:
    #   - home/sguilher/data:./requirements/mariadb  # ?
    restart: unless-stopped
    networks:
      - inception-network
    init: true

networks:
  inception-network: